apiVersion: v1
kind: Namespace
metadata:
  name: imss-ai-suite
  labels:
    name: imss-ai-suite
    app: imss-medical-ai
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imss-config
  namespace: imss-ai-suite
data:
  NODE_ENV: "production"
  FLASK_ENV: "production"
  LOG_LEVEL: "INFO"
  # URLs de servicios internos
  SERVICIO_CHATBOT_URL: "http://servicio-chatbot-service:5001"
  SERVICIO_EDUCACION_URL: "http://servicio-educacion-service:5002"
  SERVICIO_SIMULACION_URL: "http://servicio-simulacion-service:5003"
  SERVICIO_RADIOGRAFIAS_URL: "http://servicio-radiografias-service:5004"
  REDIS_URL: "redis://redis-service:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: imss-secrets
  namespace: imss-ai-suite
type: Opaque
stringData:
  MEDGEMMA_ENDPOINT: "https://your-medgemma-endpoint.com"
  LM_STUDIO_URL: "http://lm-studio:1234"
  GEMINI_API_KEY: "your-gemini-api-key-here"
  GCP_MEDGEMMA_ENDPOINT: "https://your-gcp-medgemma-endpoint.com"
  GCP_MEDGEMMA_SERVICE_ACCOUNT_KEY: '{"type": "service_account", "project_id": "your-project"}'
  SECRET_KEY: "your-secret-key-here"
  JWT_SECRET: "your-jwt-secret-here"
